### ISSUE TITLE
Server updater plugin crash

### ISSUE THREAD

**Issue by NullSoldier** [NullSoldier/serverthrall#22]
```
[serverthrall] Unloading ServerUpdater plugin after error 
Traceback (most recent call last):
  File "serverthrall\thrall.py", line 49, in start
    plugin.tick()
  File "serverthrall\plugins\intervaltickplugin.py", line 37, in tick
    self.tick_interval()
  File "serverthrall\plugins\serverupdater.py", line 106, in tick_interval
    is_available, current, target = self.is_update_available()
  File "serverthrall\plugins\serverupdater.py", line 90, in is_update_available
    self.tick_early() # if there is an error, try again
  File "serverthrall\plugins\intervaltickplugin.py", line 25, in tick_early
    self.trigger.trigger()
TypeError: trigger() takes no arguments (1 given)
```

**Comment by NullSoldier** [comment]
The issue was then it was trying to trigger early.

Fixed in e88462902d9d08548b3368542bfcd1a7b18bc1de
