### ISSUE TITLE
ServerUpdater does not work: can only load a str as an ACF

### ISSUE THREAD

**Issue by iv-mexx** [NullSoldier/serverthrall#39]
I'm encountering this error with Serverthrall when its necessary to update the server:

```[serverthrall] Unloading ServerUpdater plugin after error
Traceback (most recent call last):
  File "D:\Documents\GitHub\serverthrall\serverthrall\thrall.py", line 55, in start
    plugin.tick()
  File "D:\Documents\GitHub\serverthrall\serverthrall\plugins\intervaltickplugin.py", line 39, in tick
    self.tick_interval()
  File "D:\Documents\GitHub\serverthrall\serverthrall\plugins\serverupdater.py", line 110, in tick_interval
    is_available, current, target = self.is_update_available()
  File "D:\Documents\GitHub\serverthrall\serverthrall\plugins\serverupdater.py", line 84, in is_update_available
    available_build_id, exc = self.get_available_build_id()
  File "D:\Documents\GitHub\serverthrall\serverthrall\plugins\serverupdater.py", line 59, in get_available_build_id
    app_info = self.steamcmd.get_app_info(settings.CONAN_SERVER_APP_ID)
  File "D:\Documents\GitHub\serverthrall\serverthrall\steamcmd.py", line 67, in get_app_info
    return acf.loads('\n'.join(acf_output))
  File "C:\Python27\lib\site-packages\steamfiles\acf.py", line 15, in loads
    raise TypeError('can only load a str as an ACF')
TypeError: can only load a str as an ACF
```

**Comment by NullSoldier** [comment]
This is a little odd, I really did investigate this deeply. The only issue that could be happening here is that a bytes type is being passed in. I couldn't reproduce this locally and It shouldn't be happening.

* Add better error messaging to steamfiles https://github.com/leovp/steamfiles/pull/7
* Added some workarounds in https://github.com/NullSoldier/serverthrall/pull/40

If this comes up again I'm going to try and reproduce this another way. Could you by any chance download the latest EXE and see if this fixes it?

**Comment by iv-mexx** [comment]
I will check your fix later today. 
By the way, I did not use the exe because I tried to test https://github.com/NullSoldier/serverthrallapi/pull/6 and thus had to change the API url to my local server

**Comment by NullSoldier** [comment]
OH OH OH!!! The issue is obvious to me then. I upgraded the project to
Python v3.6 which is a HUGE upgrade.

If you have python 3 installed you can create a 3.6 virtualenv by using
"python3 -m venv virtualenv"

I'll test your change and then merge on the API side

**Comment by iv-mexx** [comment]
Oh lol, ok I'll do and try again when I come home today
