### ISSUE TITLE
RemoteConsole crash in 2.3.1

### ISSUE THREAD

**Issue by NullSoldier** [NullSoldier/serverthrall#63]
```
[serverthrall.RestartManager] The server is being restarted in 5 minutes.

Traceback (most recent call last):
  File "serverthrall\plugins\remoteconsole.py", line 31, in execute_safe
  File "lib\site-packages\valve\rcon.py", line 325, in __enter__
  File "lib\site-packages\valve\rcon.py", line 464, in wrapper
  File "lib\site-packages\valve\rcon.py", line 464, in wrapper
  File "lib\site-packages\valve\rcon.py", line 483, in connect
OSError: [WinError 10049] The requested address is not valid in its context
```

**Comment by NullSoldier** [comment]
done
