### ISSUE TITLE
Discord plugin crashes when message fails on 2.1.3

### ISSUE THREAD

**Issue by NullSoldier** [NullSoldier/serverthrall#64]
```
2018-05-20 13:44:56|ERROR|serverthrall] Unloading Discord plugin after error 
Traceback (most recent call last):
  File "serverthrall\thrall.py", line 54, in _tick_plugins
  File "serverthrall\plugins\intervaltickplugin.py", line 39, in tick
  File "serverthrall\plugins\discord.py", line 27, in tick_interval
  File "serverthrall\plugins\discord.py", line 75, in try_failed_messages
IndexError: list index out of range
```

**Comment by NullSoldier** [comment]
Fixed in 2.1.4
