### ISSUE TITLE
Non english characters in RCON breaks RCON

### ISSUE THREAD

**Issue by NullSoldier** [NullSoldier/serverthrall#65]
```
Traceback (most recent call last):
  File "serverthrall\plugins\remoteconsole.py", line 32, in execute_safe
  File "lib\site-packages\valve\rcon.py", line 464, in wrapper
  File "lib\site-packages\valve\rcon.py", line 464, in wrapper
  File "lib\site-packages\valve\rcon.py", line 571, in execute
  File "lib\site-packages\valve\rcon.py", line 399, in _request
  File "lib\site-packages\valve\rcon.py", line 107, in __init__
  File "lib\site-packages\valve\rcon.py", line 142, in text
UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-16: ordinal not in range(128)
```

**Comment by NullSoldier** [comment]
done
