### ISSUE TITLE
Uptime tracker crashes with empty fields

### ISSUE THREAD

**Issue by NullSoldier** [NullSoldier/serverthrall#77]
Config
```
[UptimeTracker]
enabled = false
initial = 
seconds_up = 
uptime_percent =
```

STack trace
```
[2018-06-06 20:22:57|INFO|serverthrall] Launching server and waiting for child processes with extra arguments, -log -MULTIHOME=142.44.143.171 -nosteam
[2018-06-06 20:22:57|INFO|serverthrall] Setting server process to high priority
[2018-06-06 20:22:57|INFO|serverthrall] Server running successfully
[2018-06-06 20:22:58|INFO|serverthrall.ServerUpdater] Auto updater ready, currently known buildid is 2804283
[2018-06-06 20:22:58|ERROR|serverthrall] Unloading UptimeTracker plugin after error 
Traceback (most recent call last):
  File "serverthrall\thrall.py", line 27, in unload_plugin
  File "serverthrall\thrall.py", line 69, in _load_plugins
  File "serverthrall\plugins\uptimetracker.py", line 29, in ready
  File "serverthrall\appconfig\sectionforcedconfig.py", line 14, in wrapper
  File "serverthrall\appconfig\sectionforcedconfig.py", line 38, in getfloat
  File "configparser.py", line 824, in getfloat
  File "configparser.py", line 809, in _get_conv
  File "configparser.py", line 803, in _get
ValueError: could not convert string to float: 
[2018-06-06 20:22:58|ERROR|serverthrall] Traceback (most recent call last):
  File "serverthrall\thrall.py", line 27, in unload_plugin
  File "serverthrall\thrall.py", line 69, in _load_plugins
  File "serverthrall\plugins\uptimetracker.py", line 29, in ready
  File "serverthrall\appconfig\sectionforcedconfig.py", line 14, in wrapper
  File "serverthrall\appconfig\sectionforcedconfig.py", line 38, in getfloat
  File "configparser.py", line 824, in getfloat
  File "configparser.py", line 809, in _get_conv
  File "configparser.py", line 803, in _get
ValueError: could not convert string to float: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 15, in <module>
  File "serverthrall__init__.py", line 114, in run_server_thrall
  File "serverthrall\thrall.py", line 42, in start
  File "serverthrall\thrall.py", line 73, in _load_plugins
  File "serverthrall\thrall.py", line 32, in unload_plugin
  File "serverthrall\plugins\uptimetracker.py", line 37, in unload
  File "serverthrall\plugins\uptimetracker.py", line 59, in update_time
AttributeError: 'UptimeTracker' object has no attribute 'seconds_up'

[2018-06-06 20:22:58|INFO|serverthrall] Safely shutting down server thrall...
[2018-06-06 20:22:58|INFO|serverthrall] Stopping ServerThrall
[2018-06-06 21:25:06|INFO|serverthrall] Running version 2.1.6
```

**Comment by NullSoldier** [comment]
https://github.com/NullSoldier/serverthrall/compare/fix-config-crash?expand=1
